### ISSUE TITLE
The lastest nodebb crash

### ISSUE THREAD

**Issue by YuriSizuku** [DaZiYuan/nodebb-plugin-dbsearch-chinese#1]
The logs is as below

error: TypeError: callback is not a function
    at D:\MAKE\Network\yurisbbs\node_modules\nodebb-plugin-dbsearch-for-chinese\lib\mongo.js:143:11
    at D:\MAKE\Network\yurisbbs\node_modules\mongodb\lib\utils.js:677:5
    at handleCallback (D:\MAKE\Network\yurisbbs\node_modules\mongodb\lib\utils.js:102:55)
    at D:\MAKE\Network\yurisbbs\node_modules\mongodb\lib\cursor.js:838:66
    at D:\MAKE\Network\yurisbbs\node_modules\mongodb\lib\utils.js:677:5
    at D:\MAKE\Network\yurisbbs\node_modules\mongodb\lib\cursor.js:923:9
    at AggregationCursor._endSession (D:\MAKE\Network\yurisbbs\node_modules\mongodb\lib\core\cursor.js:394:7)
    at D:\MAKE\Network\yurisbbs\node_modules\mongodb\lib\cursor.js:921:12
    at maybePromise (D:\MAKE\Network\yurisbbs\node_modules\mongodb\lib\utils.js:665:3)
    at AggregationCursor.close (D:\MAKE\Network\yurisbbs\node_modules\mongodb\lib\cursor.js:914:12)
2020-11-13T16:34:33.481Z [4567/16476] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2020-11-13T16:34:33.481Z [4567/16476] - info: [app] Web server closed to connections.
2020-11-13T16:34:33.482Z [4567/16476] - error: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.

**Comment by phoeson** [comment]
我试了一下，会出错
